import type { UiText } from "./uiText";
import { uiTextJa } from "./uiText";

/**
 * 英語辞書。段階移行のため、未翻訳キーは日本語辞書を継承する。
 */
export const uiTextEn: UiText = {
  ...uiTextJa,
  actionLinks: {
    aria: {
      navigation: "Navigation links",
    },
  },
  navigation: {
    dashboard: "Dashboard",
    definitions: "Definitions",
    executions: "Executions",
    health: "Health",
    adminUsers: "Users",
    adminGroups: "Groups",
  },
  entities: {
    definition: "Definition",
    execution: "Execution",
    node: "Node",
  },
  lists: {
    ...uiTextJa.lists,
    executions: "Executions",
    definitions: "Definitions",
    nodeCount: (count: number) => `${count} items`,
  },
  actions: {
    ...uiTextJa.actions,
    load: "Load",
    loading: "Loading...",
    reload: "Reload",
    cancel: "Cancel",
    resume: "Resume",
    retry: "Retry",
    save: "Save",
    sendEvent: "Send event",
    openDetail: "Details",
    closeToast: "Close notification",
    viewList: "List",
    viewGraph: "Graph",
  },
  pagination: {
    prev: "Prev",
    next: "Next",
  },
  auth: {
    login: {
      title: "Sign in",
      description: "Sign in with your tenant key and account credentials.",
      tenantKeyLabel: "Tenant key",
      emailLabel: "Email",
      passwordLabel: "Password",
      showPassword: "Show password",
      hidePassword: "Hide password",
      submit: "Sign in",
      submitting: "Signing in…",
      sessionHint: "Or sign in at /login.",
    },
    errors: {
      network: "A network error occurred. Check your connection and try again.",
      unexpectedResponse: "The sign-in response was invalid. Contact your administrator.",
    },
  },
  admin: {
    users: {
      title: "User management",
      description: "List, create, and enable or disable users in this tenant.",
      createTitle: "Create user",
      emailLabel: "Email",
      passwordLabel: "Initial password",
      displayNameLabel: "Display name (optional)",
      isTenantAdminLabel: "Tenant administrator",
      createSubmit: "Create",
      creating: "Creating…",
      active: "Active",
      inactive: "Inactive",
      disable: "Disable",
      enable: "Enable",
      adminBadge: "Admin",
      groupCount: (count: number) => `${count} group(s)`,
      forbidden: "Tenant administrators only.",
    },
    groupManagement: {
      title: "Group management",
      description: "Create groups and assign members and permissions.",
      createTitle: "Create group",
      nameLabel: "Group name",
      createSubmit: "Create",
      creating: "Creating…",
      membersTitle: "Members",
      permissionsTitle: "Permissions",
      saveMembers: "Save members",
      savePermissions: "Save permissions",
      saving: "Saving…",
      systemBadge: "System",
      memberCount: (count: number) => `${count} member(s)`,
      permissionCount: (count: number) => `${count} permission(s)`,
      openDetail: "Edit",
      backToList: "Back to groups",
      forbidden: "Tenant administrators only.",
    },
    permissions: {
      label: (displayKey: string | null | undefined, displayLabel: string) => displayKey ?? displayLabel,
    },
  },
  labels: {
    ...uiTextJa.labels,
    status: "Status",
    nodeId: "Node ID",
    definitionId: "Definition ID",
    displayId: "Display ID",
    resourceId: "Resource ID",
    graphId: "Graph ID",
    input: "Input",
    definitionEditor: "Definition Editor",
  },
  errorPrefixes: {
    unauthorized401: "401 Authentication required",
    forbidden403: "403 Insufficient permission or tenant is missing",
    conflict409: "409 State conflict",
    unprocessable422: "422 Invalid input",
    server500: "500 Server error",
  },
  executionDashboard: {
    ...uiTextJa.executionDashboard,
    header: {
      titleDefault: "Execution detail",
    },
    actions: {
      sectionTitle: "Execution actions",
      eventNameLabel: "Event name",
      eventNamePlaceholder: "event-name",
    },
    validation: {
      eventNameTooLong: "Event name must be within 64 characters.",
      eventNameInvalidFormat: "Event name must start with an ASCII letter and use only ASCII alphanumerics plus . - _.",
    },
    graph: {
      fullscreenEnter: "Fullscreen",
      fullscreenExit: "Exit fullscreen (Esc)",
      definitionMissingFallback: (graphId: string) =>
        `No registered graph definition for graph ID ${graphId}. Showing temporary edges.`,
    },
    errors: {
      executionNotFound: "The specified execution was not found. Please check the ID.",
    },
    toasts: {
      cancelAccepted: "CancelExecution accepted",
      publishAccepted: "PublishEvent accepted",
      resumeAccepted: "ResumeNode accepted",
    },
    replayDisabledReason: "Actions are disabled while replaying.",
    operationsAggregatedInRun: (cancelLabel: string, resumeLabel: string, sendEventLabel: string) =>
      `${cancelLabel} / ${resumeLabel} / ${sendEventLabel} are grouped in the Run screen.`,
  },
  executionTimeline: {
    ...uiTextJa.executionTimeline,
    title: "Event timeline",
    backToCurrent: "Back to current",
    replayingPastStateMessage: 'Showing a past state. Click "Back to current" to return to the latest state.',
    empty: "No events",
    loadMore: "Load more",
    errorUnknown: "An unknown error occurred.",
  },
  executionComparison: {
    ...uiTextJa.executionComparison,
    title: "Compare two executions",
    executionIdPlaceholder: "ex-2",
    executionABaselineLabel: (executionLabel: string) => `${executionLabel} A (baseline)`,
    executionBLabel: (executionLabel: string) => `${executionLabel} B`,
    kind: {
      onlyLeft: "A only",
      onlyRight: "B only",
      diff: "Diff",
    },
    state: {
      notLoaded: "Not loaded",
    },
    summary: {
      title: "Diff summary",
      failedOrCancelled: "Failed / Cancelled",
      others: "Others",
      noDiff: "No node differences",
      loadBothToShow: "Load A and B to show differences.",
    },
  },
  nodeDetail: {
    ...uiTextJa.nodeDetail,
    prompts: {
      loadExecution: (executionLabel: string) => `Please load ${executionLabel}.`,
      selectNode: (nodeLabel: string) => `Please select ${nodeLabel}.`,
    },
    title: (nodeLabel: string) => `${nodeLabel} detail`,
    meta: {
      type: (nodeType: string) => `Type: ${nodeType}`,
      stateName: (stateName: string) => `Node name: ${stateName}`,
      executionNodeId: (id: string) => `Execution node ID: ${id}`,
      workerId: (workerId: string) => `Worker ID: ${workerId}`,
      attempt: (attempt: number) => `Attempts: ${attempt}`,
      waitKey: (waitKey: string) => `Wait key: ${waitKey}`,
      canceledByExecution: (canceledByExecution: boolean) => `Canceled: ${String(canceledByExecution)}`,
    },
    waiting: {
      title: "Waiting",
      reasonWaitByWaitKeyAndResumeWait: "Reason: waiting for resume event by wait key",
      resumeEventName: (eventName: string) => `Resume event name: ${eventName}`,
    },
    cancel: {
      detailTitle: (cancelLabel: string) => `${cancelLabel} detail`,
      convergedByExecutionCancel: "Converged by execution cancellation",
    },
    failure: {
      title: "Failure",
      noMessage: "(No message)",
    },
    trace: {
      startedAt: (formattedInstant: string) => `Started: ${formattedInstant}`,
      completedAt: (formattedInstant: string) => `Completed: ${formattedInstant}`,
      duration: (durationText: string) => `Duration: ${durationText}`,
      durationUnavailable: "Duration: —",
      outputHeading: "Output",
      outputEmpty: "(None)",
      inputHeading: "Input",
      inputEmpty: "(None)",
      conditionRoutingHeading: "Condition routing",
      conditionRoutingEmpty: "(None)",
    },
  },
  graphLegend: {
    ...uiTextJa.graphLegend,
    heading: {
      nodeStatus: "Node status",
      edgeType: "Edge type",
    },
    aria: {
      root: "Graph legend",
      nodeStatus: "Node status legend",
      edgeType: "Edge type legend",
    },
    edgeKind: {
      nextTraversed: "Next (executed path)",
      nextNotTraversed: "Next (not traversed)",
    },
  },
  executionHeader: {
    ...uiTextJa.executionHeader,
    placeholderExecutionId: "ex-1",
    executionIdLabel: (executionLabel: string) => `${executionLabel} ID`,
    compareLabel: "Compare",
    realtimeSseLabel: "Realtime updates",
    cancelRequestedLabel: "Cancel requested",
    graphIdLine: (graphIdLabel: string, graphId: string) => `${graphIdLabel}: ${graphId}`,
    cancelRequestedLine: (cancelRequestedLabel: string, cancelRequested: boolean) =>
      `${cancelRequestedLabel}: ${cancelRequested ? "Yes" : "No"}`,
  },
  pageState: {
    loading: "Loading...",
    empty: "No data to display.",
    error: "Failed to load data.",
  },
  dashboard: {
    ...uiTextJa.dashboard,
    title: "Dashboard",
    descriptionRecent: "Recent executions (up to 10).",
    loadingRecent: "Loading recent executions.",
    emptyStartFromDefinitionsOrExecutions: "Start from Definitions or Executions.",
    totalCount: (count: number | null) => (count == null ? "Total: --" : `Total: ${count}`),
    updatedAt: (formattedDateTime: string) => `Updated: ${formattedDateTime}`,
    aria: {
      recentExecutionsList: "Recent executions",
    },
    actions: {
      openDetail: "Open details",
    },
    error: {
      fetchFailed: "Failed to fetch data.",
    },
  },
  executionsPage: {
    ...uiTextJa.executionsPage,
    loading: "Loading executions.",
    listSummary: (totalCount: number, page: number) => `Total ${totalCount} (page ${page})`,
    updatedAt: (formattedDateTime: string) => `Updated: ${formattedDateTime}`,
    empty: "No executions found.",
    error: "Failed to load executions. Please try again later.",
    pagination: {
      ...uiTextJa.executionsPage.pagination,
      ariaLabel: "Executions pagination",
      currentPage: (page: number) => `Page ${page}`,
      prev: "Prev",
      next: "Next",
    },
    filter: {
      ...uiTextJa.executionsPage.filter,
      contextActivePrefix: "Definition filter:",
      clearDefinition: "Clear definition filter",
      title: "Filters",
      all: "(All)",
      statusRunning: "Running",
      statusCompleted: "Completed",
      statusCancelled: "Cancelled",
      statusFailed: "Failed",
      definitionInputHint: "Definition display ID / UUID",
      definitionLabelWithHint: (definitionLabel: string) => `${definitionLabel} (display ID / UUID)`,
      definitionPlaceholder: "e.g. def-...",
      nameInputHint: "name (execution display ID partial match, or execution UUID exact match)",
      search: "Search",
      clear: "Clear",
      sortByLabel: "Sort by",
      sortOrderLabel: "Order",
      sortByUpdatedAt: "Updated at",
      sortByDisplayId: "Display ID",
      sortOrderDesc: "Descending",
      sortOrderAsc: "Ascending",
      invalidName: "Name allows only ASCII alphanumerics plus . - _ within 100 characters.",
      invalidDefinitionId: "Definition ID allows only ASCII alphanumerics plus - _ within 80 characters.",
      pageInfo: (limit: number, offset: number, page: number) =>
        `Items per page: ${limit}. Offset: ${offset} (approx. page ${page})`,
    },
    actions: {
      openDetail: "Details",
    },
  },
  definitionsPage: {
    ...uiTextJa.definitionsPage,
    description: "Search and paginate definitions, then open the detail page.",
    loading: "Loading definitions.",
    emptyNoMatch: "No definitions matched. Change the query or clear filters.",
    searchSummaryPrefix: (keyword: string) => `Search: "${keyword}" / `,
    listSummary: (totalCount: number, page: number) => `Total ${totalCount} (page ${page})`,
    createdAt: (formattedDateTime: string) => `Created: ${formattedDateTime}`,
    error: "Failed to load definitions.",
    pagination: {
      ...uiTextJa.definitionsPage.pagination,
      ariaLabel: "Definitions pagination",
      currentPage: (page: number) => `Page ${page}`,
    },
    search: {
      label: "Name search (partial match)",
      placeholder: "e.g. order",
      submit: "Search",
      clear: "Clear",
      invalidName: "Search keyword allows only ASCII alphanumerics plus . - _ within 100 characters.",
    },
    sortByLabel: "Sort by",
    sortOrderLabel: "Order",
    sortByCreatedAt: "Created at",
    sortByName: "Name",
    sortOrderDesc: "Descending",
    sortOrderAsc: "Ascending",
    actions: {
      openDetail: "Open details",
      createNew: "Create new definition",
    },
  },
  executionDetailPage: {
    ...uiTextJa.executionDetailPage,
    title: "Execution detail",
    missingExecutionId: "Execution ID is missing.",
    navRun: "Run",
    navGraph: "Graph",
  },
  executionGraphPage: {
    ...uiTextJa.executionGraphPage,
    title: "Execution graph",
    missingExecutionId: "Execution ID is missing.",
    navDetail: "Detail",
    navRun: "Run",
  },
  executionRunPage: {
    ...uiTextJa.executionRunPage,
    title: "Execution run",
    missingExecutionId: "Execution ID is missing.",
    navDetail: "Detail",
    navGraph: "Graph",
  },
  definitionRunPage: {
    ...uiTextJa.definitionRunPage,
    title: "Run definition",
    unspecifiedDefinitionId: "(not specified)",
    inputLabelWithHint: (inputLabel: string) => `${inputLabel} (optional, JSON)`,
    inputJsonPlaceholder: 'Example: {"orderId":"123"}',
    nav: {
      backToDefinitionDetail: "Back to definition detail",
    },
    actions: {
      starting: "Starting...",
      startExecution: "Start execution",
    },
    toasts: {
      definitionIdRequired: (definitionIdLabel: string) => `${definitionIdLabel} is required.`,
      invalidInputJson: (inputLabel: string) => `${inputLabel} JSON is invalid.`,
      inputTooLarge: "Input must be within 65536 bytes (64KiB).",
      executionStarted: (executionDisplayId: string) => `Execution started: ${executionDisplayId}`,
    },
    help: {
      redirectAfterStart: (runPath: string) => `After starting, you will be redirected to ${runPath}.`,
    },
  },
  definitionDetail: {
    ...uiTextJa.definitionDetail,
    title: "Definition detail",
    urlPrefix: "URL:",
    errorFetchFailed: "Failed to fetch definition.",
    ariaMeta: "Definition metadata",
    meta: {
      name: "Name",
      createdAt: "Created at",
    },
    relatedExecutions: {
      title: "Related executions",
      description: "Go to the list of executions related to this definition.",
      openList: "Open executions list",
    },
    actions: {
      title: "Edit / Run",
      edit: "Edit definition",
      run: "Start new execution",
    },
    nav: {
      backToDefinitions: "Back to definitions",
    },
  },
  definitionEditor: {
    ...uiTextJa.definitionEditor,
    backToDetail: "Back to definition detail",
    descriptionCreating: "Create a new definition.",
    descriptionEditingTarget: (definitionId: string) => `Editing target: ${definitionId}`,
    loadingMeta: "Loading definition metadata...",
    validation: {
      nameRequired: "Please enter a definition name.",
      yamlRequired: "Please enter YAML.",
      yamlLintInvalid: "Please fix YAML syntax errors.",
      nameInvalidFormat: "Definition name must start with an ASCII letter and use only ASCII alphanumerics plus . - _ within 100 characters.",
      yamlTooLarge: "YAML must be within 256KB (262144 bytes).",
    },
    labels: {
      name: "Definition name (name)",
      yaml: "YAML",
    },
    actions: {
      saving: "Saving...",
      saveWithApiHint: "Save",
      resetTemplate: "Reset to initial",
      switchToYaml: "YAML",
      switchToGraph: "Graph",
    },
    graph: {
      title: "Graph editor",
      empty: "Graph cannot be shown because YAML parsing failed. Please fix YAML first.",
      addNode: "Add node",
      addNodeDialogTitle: "Add node",
      addNodeDisabledReasonStart: "Only one start node is allowed.",
      addNodeDisabledReasonEnd: "Only one end node is allowed.",
      nodeInspectorTitle: "Node inspector",
      edgeInspectorTitle: "Edge inspector",
      deleteNode: "Delete node",
      deleteEdge: "Delete edge",
      apply: "Apply",
      closeDialog: "Close",
      rootObjectRequired: () => "YAML root must be an object.",
      nodesArrayRequired: () => "nodes must be an array.",
      nodesRequired: () => "nodes requires at least one item.",
      nodeIdRequired: () => "node.id is required.",
      duplicateNodeId: (nodeId: string) => `Duplicate node.id: '${nodeId}'`,
      startCountInvalid: (count: number) => `Exactly one start node is required (current: ${count}).`,
      endCountInvalid: (count: number) => `Exactly one end node is required (current: ${count}).`,
      startRequiresTransition: (nodeId: string) => `Node '${nodeId}': start requires next or edges.`,
      actionRequired: (nodeId: string) => `Node '${nodeId}': action node requires action.`,
      actionRequiresTransition: (nodeId: string) => `Node '${nodeId}': action requires next or edges.`,
      waitEventRequired: (nodeId: string) => `Node '${nodeId}': wait node requires event.`,
      waitRequiresTransition: (nodeId: string) => `Node '${nodeId}': wait requires next or edges.`,
      forkBranchesRequired: (nodeId: string) => `Node '${nodeId}': fork requires at least two branches.`,
      joinRequiresTransition: (nodeId: string) => `Node '${nodeId}': join requires next or edges.`,
      joinModeInvalid: (nodeId: string) => `Node '${nodeId}': join.mode must be 'all'.`,
      endCannotHaveTransition: (nodeId: string) => `Node '${nodeId}': end cannot have next/edges.`,
      edgeToRequired: (nodeId: string) => `Node '${nodeId}': edge.to is required.`,
      edgeWhenPathRequired: (nodeId: string) => `Node '${nodeId}': edge.when.path is required.`,
      edgeWhenOpRequired: (nodeId: string) => `Node '${nodeId}': edge.when.op is required.`,
      edgeWhenValueRequired: (nodeId: string) =>
        `Node '${nodeId}': edge.when.value is required for this operator (not EXISTS).`,
      edgeWhenValueInInvalid: (nodeId: string) =>
        `Node '${nodeId}': IN requires a non-empty array (or JSON array string) for edge.when.value.`,
      edgeWhenValueBetweenInvalid: (nodeId: string) =>
        `Node '${nodeId}': BETWEEN requires an array of at least two values (or JSON array string) for edge.when.value.`,
      edgeDefaultMultiple: (nodeId: string) =>
        `Node '${nodeId}': only one edge can have default=true.`,
      selfReferenceEdge: (nodeId: string) => `Node '${nodeId}': self-referencing edge is not allowed.`,
      missingTargetNode: (nodeId: string, targetId: string) => `Node '${nodeId}': target '${targetId}' does not exist.`,
      selfReferenceRejected: "Self-referencing edges are not allowed.",
      whenOpPlaceholder: "Select operator",
      whenPathPlaceholder: "$.payload.amount",
      whenValuePlaceholder: "e.g. 100 / true / \"100\"",
      whenValueDisabledForExists: "Value is not required for EXISTS.",
      whenValueHintIn: "For IN, enter a JSON array. Example: [\"A\", \"B\"]",
      whenValueHintBetween: "For BETWEEN, enter [min, max] as a JSON array. Example: [1, 10]",
      fullscreenEnter: "Fullscreen",
      fullscreenExit: "Exit fullscreen",
      parseFailed: "YAML parsing failed. Keeping the previous valid graph.",
      actionErrorLabel: "Error transition (optional)",
      actionInputLabel: "input (optional)",
      actionInputPlaceholder: 'e.g. $.input.orderId or {"orderId":"$.input.orderId"}',
      actionInputHint: "Paths use $ / $. only. Enter objects as JSON.",
      actionInputInvalidJson: "Invalid JSON.",
    },
    saved: {
      completePrefix: "Saved:",
      complete: (displayId: string) => `Saved: ${displayId}`,
      openNewDetail: "Open new definition detail",
      runWithThisDefinition: "Run with this definition",
    },
    toasts: {
      savedWithDisplayId: (displayIdLabel: string, displayId: string) =>
        `Definition saved (${displayIdLabel}: ${displayId})`,
    },
    hints: {
      title: "Fix hints",
    },
  },
  tenantMissingBanner: {
    noticeParts: (loadLabel: string, cancelLabel: string, resumeLabel: string) => ({
      beforePrimaryEnv: `Tenant is not set. ${loadLabel} / ${cancelLabel} / ${resumeLabel} may fail. Set `,
      betweenEnvs: " or configure ",
      afterSecondaryEnv: " in the server environment.",
    }),
  },
  executionStatusBanner: {
    cancelRequestedNotice: (cancelLabel: string, resumeLabel: string) =>
      `${cancelLabel} already requested, so progress actions like ${resumeLabel} are disabled.`,
    terminalNotice: (executionLabel: string) => `${executionLabel} is already finished.`,
  },
  nodeList: {
    ...uiTextJa.nodeList,
    title: "Node list",
    nodeCount: (count: number) => `${count} items`,
    columns: {
      status: "Status",
      type: "Type",
      nodeName: "Node name",
      executionNodeId: "Execution node ID",
      duration: "Duration",
    },
  },
  nodeGraph: {
    meta: {
      type: (nodeType: string) => `Type: ${nodeType}`,
      attempt: (attempt: number) => `Attempts: ${attempt}`,
      waitKey: (waitKey: string) => `Wait key: ${waitKey}`,
    },
    aria: {
      selectNode: (displayLabel: string) => `Select node: ${displayLabel}`,
    },
  },
  nodeCommands: {
    resumeDisabledReason: {
      runOnly: "Resume is available only on the Run screen.",
      executionNotLoaded: "Execution is not loaded.",
      nodeNotSelected: "Please select a node.",
      executionTerminal: "Execution is already finished.",
      cancelRequested: "Cancel was requested, so progress actions like Resume are disabled.",
      waitingOnly: "Resume is available only for WAITING nodes.",
    },
  },
};

