// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Statevia.Infrastructure.Persistence;

#nullable disable

namespace Statevia.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    [Migration("20260708160850_AddDefinitionsDeletedAt")]
    partial class AddDefinitionsDeletedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Statevia.Core.Application.Contracts.Persistence.CommandDedupRow", b =>
                {
                    b.Property<string>("DedupKey")
                        .HasColumnType("text")
                        .HasColumnName("dedup_key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endpoint");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("RequestHash")
                        .HasColumnType("text")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("text")
                        .HasColumnName("response_body");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.HasKey("DedupKey");

                    b.ToTable("command_dedup", (string)null);
                });

            modelBuilder.Entity("Statevia.Core.Application.Contracts.Persistence.DefinitionRow", b =>
                {
                    b.Property<Guid>("DefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("definition_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("LatestVersion")
                        .HasColumnType("integer")
                        .HasColumnName("latest_version");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("slug");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("DefinitionId");

                    b.HasIndex("TenantId");

                    b.HasIndex("ProjectId", "Slug")
                        .IsUnique()
                        .HasFilter("\"deleted_at\" IS NULL");

                    b.ToTable("definitions", (string)null);
                });

            modelBuilder.Entity("Statevia.Core.Application.Contracts.Persistence.DefinitionVersionRow", b =>
                {
                    b.Property<Guid>("DefinitionVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("definition_version_id");

                    b.Property<string>("CompiledJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("compiled_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("definition_id");

                    b.Property<string>("SourceYaml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_yaml");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("DefinitionVersionId");

                    b.HasIndex("DefinitionId", "Version")
                        .IsUnique();

                    b.ToTable("definition_versions", (string)null);
                });

            modelBuilder.Entity("Statevia.Core.Application.Contracts.Persistence.DisplayIdRow", b =>
                {
                    b.Property<string>("Kind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("display_id");

                    b.HasKey("Kind", "ResourceId");

                    b.HasIndex("DisplayId")
                        .IsUnique();

                    b.ToTable("display_ids", (string)null);
                });

            modelBuilder.Entity("Statevia.Core.Application.Contracts.Persistence.EventDeliveryDedupRow", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_id");

                    b.Property<Guid>("ClientEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_event_id");

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTime?>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("error_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TenantId", "ExecutionId", "ClientEventId");

                    b.HasIndex("TenantId", "ExecutionId", "BatchId");

                    b.ToTable("event_delivery_dedup", (string)null);
                });

            modelBuilder.Entity("Statevia.Core.Application.Contracts.Persistence.EventStoreRow", b =>
                {
                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_id");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    b.Property<string>("ActorId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorKind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("actor_kind");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uuid")
                        .HasColumnName("causation_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("type");

                    b.HasKey("ExecutionId", "Seq");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("event_store", (string)null);
                });

            modelBuilder.Entity("Statevia.Core.Application.Contracts.Persistence.ExecutionCursorRow", b =>
                {
                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_id");

                    b.Property<string>("CurrentNodeId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("current_node_id");

                    b.Property<string>("CurrentRuntimeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("current_runtime_id");

                    b.Property<string>("CurrentWorkerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("current_worker_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ExecutionId");

                    b.HasIndex("TenantId");

                    b.ToTable("execution_cursors", (string)null);
                });

            modelBuilder.Entity("Statevia.Core.Application.Contracts.Persistence.ExecutionGraphSnapshotRow", b =>
                {
                    b.Property<Guid>("ExecutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("execution_id");

                    b.Property<string>("GraphJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("graph_json");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ExecutionId");

                    b.ToTable("execution_graph_snapshots", (string)null);
                });

            modelBuilder.Entity("Statevia.Core.Application.Contracts.Persistence.ExecutionRow", b =>
                {
                    b.Property<Guid>("ExecutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("execution_id");

                    b.Property<bool>("CancelRequested")
                        .HasColumnType("boolean")
                        .HasColumnName("cancel_requested");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("definition_id");

                    b.Property<Guid>("DefinitionVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("definition_version_id");

                    b.Property<bool>("RestartLost")
                        .HasColumnType("boolean")
                        .HasColumnName("restart_lost");

                    b.Property<string>("SecuritySnapshotJson")
                        .HasColumnType("text")
                        .HasColumnName("security_snapshot_json");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ExecutionId");

                    b.HasIndex("DefinitionVersionId");

                    b.HasIndex("TenantId");

                    b.ToTable("executions", (string)null);
                });

            modelBuilder.Entity("Statevia.Core.Application.Contracts.Persistence.ExecutionWaitRow", b =>
                {
                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_id");

                    b.Property<string>("NodeId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("node_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ResumeToken")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("resume_token");

                    b.Property<string>("WaitKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("wait_kind");

                    b.HasKey("ExecutionId", "NodeId");

                    b.HasIndex("ExecutionId", "ResumeToken");

                    b.ToTable("execution_waits", (string)null);
                });

            modelBuilder.Entity("Statevia.Core.Application.Contracts.Persistence.ProjectAccessRow", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.HasKey("ProjectId", "TenantId");

                    b.HasIndex("TenantId");

                    b.ToTable("project_accesses", (string)null);
                });

            modelBuilder.Entity("Statevia.Core.Application.Contracts.Persistence.ProjectRow", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<Guid>("OwnerTenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_tenant_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("slug");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("visibility");

                    b.HasKey("ProjectId");

                    b.HasIndex("OwnerTenantId", "Slug")
                        .IsUnique();

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Statevia.Core.Application.Contracts.Persistence.WorkflowDefinitionRow", b =>
                {
                    b.Property<Guid>("DefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("definition_id");

                    b.Property<string>("CompiledJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("compiled_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<string>("SourceYaml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_yaml");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("DefinitionId");

                    b.HasIndex("TenantId");

                    b.ToTable("workflow_definitions", (string)null);
                });

            modelBuilder.Entity("Statevia.Infrastructure.Persistence.ApiKeyRow", b =>
                {
                    b.Property<Guid>("ApiKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("api_key_id");

                    b.Property<string>("AllowedScopesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("allowed_scopes_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key_hash");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("key_prefix");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid")
                        .HasColumnName("principal_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("ApiKeyId");

                    b.HasIndex("TenantId", "KeyPrefix");

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("Statevia.Infrastructure.Persistence.ExecutionEventRow", b =>
                {
                    b.Property<Guid>("ExecutionEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("execution_event_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_id");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("type");

                    b.HasKey("ExecutionEventId");

                    b.ToTable("execution_events", (string)null);
                });

            modelBuilder.Entity("Statevia.Infrastructure.Persistence.GroupPermissionRow", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("PermissionKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("permission_key");

                    b.HasKey("GroupId", "PermissionKey");

                    b.ToTable("group_permissions", (string)null);
                });

            modelBuilder.Entity("Statevia.Infrastructure.Persistence.GroupRow", b =>
                {
                    b.Property<Guid>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("GroupId");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("Statevia.Infrastructure.Persistence.PermissionDefinitionRow", b =>
                {
                    b.Property<Guid>("PermissionDefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("permission_definition_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_key");

                    b.Property<string>("DisplayLabel")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_label");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deprecated");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("OwnerKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("owner_key");

                    b.Property<string>("OwnerType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("owner_type");

                    b.Property<string>("PermissionKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("permission_key");

                    b.HasKey("PermissionDefinitionId");

                    b.HasIndex("PermissionKey")
                        .IsUnique();

                    b.ToTable("permission_definitions", (string)null);
                });

            modelBuilder.Entity("Statevia.Infrastructure.Persistence.PrincipalRow", b =>
                {
                    b.Property<Guid>("PrincipalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("principal_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("PrincipalScope")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("principal_scope");

                    b.Property<string>("PrincipalType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("principal_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PrincipalId");

                    b.ToTable("principals", (string)null);
                });

            modelBuilder.Entity("Statevia.Infrastructure.Persistence.ServiceAccountGroupMemberRow", b =>
                {
                    b.Property<Guid>("ServiceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_account_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.HasKey("ServiceAccountId", "GroupId");

                    b.ToTable("service_account_group_members", (string)null);
                });

            modelBuilder.Entity("Statevia.Infrastructure.Persistence.ServiceAccountRow", b =>
                {
                    b.Property<Guid>("ServiceAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("service_account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid")
                        .HasColumnName("principal_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("ServiceAccountId");

                    b.ToTable("service_accounts", (string)null);
                });

            modelBuilder.Entity("Statevia.Infrastructure.Persistence.TenantRow", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("lifecycle");

                    b.Property<string>("TenantKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tenant_key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TenantId");

                    b.HasIndex("TenantKey")
                        .IsUnique();

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Statevia.Infrastructure.Persistence.UserGroupMemberRow", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.HasKey("UserId", "GroupId");

                    b.ToTable("user_group_members", (string)null);
                });

            modelBuilder.Entity("Statevia.Infrastructure.Persistence.UserPrincipalRow", b =>
                {
                    b.Property<Guid>("PrincipalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("principal_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("PrincipalId");

                    b.ToTable("user_principals", (string)null);
                });

            modelBuilder.Entity("Statevia.Infrastructure.Persistence.UserRow", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPlatformAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_platform_admin");

                    b.Property<bool>("IsTenantAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_tenant_admin");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Statevia.Core.Application.Contracts.Persistence.DefinitionRow", b =>
                {
                    b.HasOne("Statevia.Core.Application.Contracts.Persistence.ProjectRow", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Statevia.Infrastructure.Persistence.TenantRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Statevia.Core.Application.Contracts.Persistence.DefinitionVersionRow", b =>
                {
                    b.HasOne("Statevia.Core.Application.Contracts.Persistence.DefinitionRow", null)
                        .WithMany()
                        .HasForeignKey("DefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Statevia.Core.Application.Contracts.Persistence.EventDeliveryDedupRow", b =>
                {
                    b.HasOne("Statevia.Infrastructure.Persistence.TenantRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Statevia.Core.Application.Contracts.Persistence.ExecutionCursorRow", b =>
                {
                    b.HasOne("Statevia.Core.Application.Contracts.Persistence.ExecutionRow", null)
                        .WithMany()
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Statevia.Infrastructure.Persistence.TenantRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Statevia.Core.Application.Contracts.Persistence.ExecutionRow", b =>
                {
                    b.HasOne("Statevia.Core.Application.Contracts.Persistence.DefinitionVersionRow", null)
                        .WithMany()
                        .HasForeignKey("DefinitionVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Statevia.Infrastructure.Persistence.TenantRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Statevia.Core.Application.Contracts.Persistence.ExecutionWaitRow", b =>
                {
                    b.HasOne("Statevia.Core.Application.Contracts.Persistence.ExecutionRow", null)
                        .WithMany()
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Statevia.Core.Application.Contracts.Persistence.ProjectAccessRow", b =>
                {
                    b.HasOne("Statevia.Core.Application.Contracts.Persistence.ProjectRow", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Statevia.Infrastructure.Persistence.TenantRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Statevia.Core.Application.Contracts.Persistence.ProjectRow", b =>
                {
                    b.HasOne("Statevia.Infrastructure.Persistence.TenantRow", null)
                        .WithMany()
                        .HasForeignKey("OwnerTenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Statevia.Core.Application.Contracts.Persistence.WorkflowDefinitionRow", b =>
                {
                    b.HasOne("Statevia.Infrastructure.Persistence.TenantRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
