/**
 * ドメインイベントタイプ定義
 */
export const EVENT_TYPES = [
  "EXECUTION_CREATED",
  "EXECUTION_STARTED",
  "EXECUTION_COMPLETED",
  "EXECUTION_ARCHIVED",
  "EXECUTION_CANCEL_REQUESTED",
  "EXECUTION_CANCELED",
  "EXECUTION_FAIL_REQUESTED",
  "EXECUTION_FAILED",
  "NODE_CREATED",
  "NODE_READY",
  "NODE_STARTED",
  "NODE_PROGRESS_REPORTED",
  "NODE_WAITING",
  "NODE_RESUME_REQUESTED",
  "NODE_RESUMED",
  "NODE_SUCCEEDED",
  "NODE_FAIL_REPORTED",
  "NODE_FAILED",
  "NODE_CANCEL_REQUESTED",
  "NODE_CANCELED",
  "NODE_INTERRUPT_REQUESTED",
  "FORK_OPENED",
  "JOIN_GATE_UPDATED",
  "JOIN_PASSED"
] as const;

export type EventType = (typeof EVENT_TYPES)[number];
